/**
 * Automated Email Notification System
 * Sends alerts to HR when high stress levels are detected
 */

interface Employee {
  id: string;
  name: string;
  email: string;
  department: string;
  burnoutRisk: 'low' | 'medium' | 'high';
  lastNotified?: number;
}

const NOTIFICATION_COOLDOWN = 24 * 60 * 60 * 1000; // 24 hours in milliseconds

/**
 * Check if employee should receive notification
 * Prevents spam by enforcing 24-hour cooldown
 */
function shouldNotify(employee: Employee): boolean {
  if (employee.burnoutRisk !== 'high') return false;
  
  if (!employee.lastNotified) return true;
  
  const timeSinceLastNotification = Date.now() - employee.lastNotified;
  return timeSinceLastNotification >= NOTIFICATION_COOLDOWN;
}

/**
 * Send automated email notification
 */
export async function sendAutomatedNotification(employee: Employee): Promise<boolean> {
  if (!shouldNotify(employee)) {
    console.log(`⏭️ Skipping notification for ${employee.name} (cooldown active)`);
    return false;
  }

  try {
    // DEMO MODE: Skip actual email sending for instant response
    console.log(`📧 [DEMO] Automated notification triggered for ${employee.name} (${employee.email})`);
    console.log(`   Department: ${employee.department} | Risk: ${employee.burnoutRisk}`);
    console.log(`   ✅ In production, wellness email would be sent here`);
    
    // Update last notification time
    const now = Date.now();
    lastNotificationTime.set(employee.id, now);
    
    // Uncomment below to enable real email sending:
    /*
    const response = await fetch('/api/employees/send-email', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        employeeId: employee.id,
        employeeName: employee.name,
        employeeEmail: employee.email,
        department: employee.department,
        riskLevel: employee.burnoutRisk,
        automated: true,
        message: generateAutomatedMessage(employee),
      }),
    });

    if (!response.ok) {
      throw new Error(`Email API failed: ${response.status}`);
    }
    */

    console.log(`✅ Notification logged successfully`);
    return true;
  } catch (error) {
    console.error(`❌ Failed to send automated notification:`, error);
    return false;
  }
}

/**
 * Generate personalized automated message
 */
function generateAutomatedMessage(employee: Employee): string {
  return `Dear ${employee.name},

Our WellMind AI system has detected elevated stress indicators in your recent activity. Your well-being is important to us.

🌟 Immediate Support Available:

• Talk to your manager about workload
• Use our AI Care Assistant (available 24/7)
• Contact HR for confidential support
• Take advantage of mental health resources

📅 We recommend:

• Scheduling a 1-on-1 with your manager
• Taking a mental health day if needed
• Exploring flexible work arrangements

This is an automated wellness check-in. Your privacy is protected, and this information is confidential.

💚 You're not alone. We're here to support you.

Best regards,
WellMind Team

---
This email was automatically generated by the WellMind Burnout Intelligence System.`;
}

/**
 * Batch check all employees and send notifications
 */
export async function checkAndNotifyHighRiskEmployees(): Promise<{
  checked: number;
  notified: number;
  skipped: number;
}> {
  try {
    console.log('🔍 Checking employees for automated notifications...');

    // Fetch all employees
    const response = await fetch('/api/employees', {
      method: 'GET',
      cache: 'no-store',
    });

    if (!response.ok) {
      throw new Error('Failed to fetch employees');
    }

    const employees: Employee[] = await response.json();
    
    let notified = 0;
    let skipped = 0;

    for (const employee of employees) {
      if (employee.burnoutRisk === 'high') {
        const sent = await sendAutomatedNotification(employee);
        if (sent) {
          notified++;
        } else {
          skipped++;
        }
      }
    }

    console.log(`✅ Notification check complete: ${notified} sent, ${skipped} skipped`);

    return {
      checked: employees.length,
      notified,
      skipped,
    };
  } catch (error) {
    console.error('❌ Batch notification error:', error);
    throw error;
  }
}

/**
 * Real-time notification trigger
 * Call this when burnout risk is calculated/updated
 */
export async function triggerNotificationIfNeeded(employee: Employee): Promise<void> {
  if (employee.burnoutRisk === 'high') {
    console.log(`🚨 High burnout risk detected for ${employee.name}`);
    await sendAutomatedNotification(employee);
  }
}
